use_frameworks!

platform :ios, '8.0'

target 'CLActionView_Example' do
  pod 'CLActionView', :path => '../'

  target 'CLActionView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
